#! /usr/bin/bash

if [ "_$1" = "_" ]; then
    echo "$0 <nom de la vm>"
    exit 1
fi

NAME=$1
virt-install --connect qemu:///system --name ${NAME} --ram 2048 --os-variant=fedora31 --import --graphic=none --disk pool=libvirt,size=10,backing_store=$(pwd)/fedora-coreos-qemu.qcow2 --qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=$(pwd)/example.ign"
